# Generated by Django 5.2.17 on 2026-08-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("channel", "Required channel"), ("backup_bot", "Backup bot")],
                        max_length=16,
                    ),
                ),
                ("telegram_id", models.BigIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("label", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("weight", models.PositiveIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_telegram_id", models.BigIntegerField(blank=True, null=True)),
                ("target_telegram_id", models.BigIntegerField(blank=True, null=True)),
                ("chat_telegram_id", models.BigIntegerField(blank=True, null=True)),
                ("kind", models.CharField(db_index=True, max_length=64)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("group", "Group"),
                            ("supergroup", "Supergroup"),
                            ("channel", "Channel"),
                        ],
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("is_forum", models.BooleanField(default=False)),
                ("is_archive", models.BooleanField(default=False)),
                ("bot_is_admin", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["title", "telegram_id"],
            },
        ),
        migrations.CreateModel(
            name="TelegramUser",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(blank=True, max_length=64)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("language_code", models.CharField(blank=True, max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("archive_chat_id", models.BigIntegerField(blank=True, null=True)),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match_type",
                    models.CharField(
                        choices=[("contains", "Contains text"), ("exact", "Exact text")],
                        default="contains",
                        max_length=16,
                    ),
                ),
                ("pattern", models.CharField(max_length=500)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("delete", "Delete"),
                            ("kick", "Kick"),
                            ("mute", "Mute"),
                            ("reply", "Reply"),
                        ],
                        max_length=16,
                    ),
                ),
                ("response", models.TextField(blank=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="core.chat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArchiveRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("live", models.BooleanField(default=False)),
                ("content_types", models.JSONField(blank=True, default=list)),
                ("first_message_id", models.BigIntegerField(blank=True, null=True)),
                ("last_message_id", models.BigIntegerField(blank=True, null=True)),
                ("delay_seconds", models.PositiveIntegerField(default=1)),
                (
                    "destination_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_rules",
                        to="core.chat",
                    ),
                ),
                (
                    "source_chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_rules",
                        to="core.chat",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_rules",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("helper_enabled", models.BooleanField(default=True)),
                ("welcome_enabled", models.BooleanField(default=False)),
                ("welcome_message", models.TextField(default="Welcome, {name}!")),
                ("goodbye_enabled", models.BooleanField(default=False)),
                ("goodbye_message", models.TextField(default="Goodbye, {name}.")),
                ("verification_enabled", models.BooleanField(default=False)),
                (
                    "chat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_settings",
                        to="core.chat",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_message_id", models.BigIntegerField()),
                ("destination_message_id", models.BigIntegerField()),
                ("original_sender_id", models.BigIntegerField(blank=True, null=True)),
                ("last_source_edit_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_mappings",
                        to="core.archiverule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("history_import", "History import"),
                            ("duplicate_scan", "Duplicate scan"),
                            ("live_archive", "Live archive"),
                            ("chat_sync", "Chat sync"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FileRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_unique_id", models.CharField(db_index=True, max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("saved", "Saved"),
                            ("duplicate", "Duplicate"),
                            ("moved", "Moved"),
                            ("failed", "Failed"),
                        ],
                        default="saved",
                        max_length=16,
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="core.filerecord",
                    ),
                ),
                (
                    "mapping",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file",
                        to="core.messagemapping",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.telegramuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConnectedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("encrypted_session", models.TextField(blank=True)),
                ("phone_hint", models.CharField(blank=True, max_length=32)),
                ("is_connected", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connected_account",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="core.telegramuser",
            ),
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("thread_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="core.chat",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="archiverule",
            name="destination_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="destination_rules",
                to="core.topic",
            ),
        ),
        migrations.AddField(
            model_name="archiverule",
            name="source_topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_rules",
                to="core.topic",
            ),
        ),
        migrations.CreateModel(
            name="BanListEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_user_id", models.BigIntegerField()),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.BigIntegerField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ban_entries",
                        to="core.chat",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "telegram_user_id"), name="unique_group_ban"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="messagemapping",
            constraint=models.UniqueConstraint(
                fields=("rule", "source_message_id"), name="unique_rule_message"
            ),
        ),
        migrations.AddIndex(
            model_name="filerecord",
            index=models.Index(
                fields=["owner", "file_unique_id", "file_size"],
                name="core_filere_owner_i_3dcfc0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chat",
            constraint=models.UniqueConstraint(
                fields=("owner", "telegram_id"), name="unique_owner_chat"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("chat", "thread_id"), name="unique_chat_topic"
            ),
        ),
    ]
