# Generated by Django 5.2.17 on 2026-08-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="default_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_users",
                to="core.chat",
            ),
        ),
        migrations.AlterField(
            model_name="automationrule",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("contains", "Contains text"),
                    ("exact", "Exact text"),
                    ("file_unique_id", "Telegram file unique ID"),
                ],
                default="contains",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("history_import", "History import"),
                    ("duplicate_scan", "Duplicate scan"),
                    ("live_archive", "Live archive"),
                    ("chat_sync", "Chat sync"),
                    ("member_sync", "Member sync"),
                    ("archive_setup", "Archive setup"),
                    ("history_index", "History index"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AdminArchiveTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_chat_telegram_id", models.BigIntegerField()),
                ("thread_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_archive_topics",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "source_chat_telegram_id"),
                        name="unique_admin_archive_topic",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArchivedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_message_id", models.BigIntegerField()),
                ("sender_telegram_id", models.BigIntegerField(blank=True, null=True)),
                ("text", models.TextField(blank=True)),
                ("content_type", models.CharField(max_length=32)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                ("message_date", models.DateTimeField(blank=True, null=True)),
                ("message_link", models.URLField(blank=True, max_length=500)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indexed_messages",
                        to="core.chat",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indexed_messages",
                        to="core.telegramuser",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indexed_messages",
                        to="core.topic",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "file_size"], name="core_archiv_owner_i_ef4fda_idx"
                    ),
                    models.Index(
                        fields=["owner", "content_type"], name="core_archiv_owner_i_e1adde_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "chat", "telegram_message_id"),
                        name="unique_indexed_message",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_user_id", models.BigIntegerField()),
                ("username", models.CharField(blank=True, max_length=64)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("is_bot", models.BooleanField(default=False)),
                ("status", models.CharField(default="member", max_length=32)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.chat",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chat", "telegram_user_id"), name="unique_chat_member"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RequirementCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="core.accessrequirement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_completions",
                        to="core.telegramuser",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "requirement"), name="unique_requirement_completion"
                    )
                ],
            },
        ),
    ]
